# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_close_proposal_proposals_proposal_id_close_patch(self) -> None:
        """Test case for close_proposal_proposals_proposal_id_close_patch

        Close Proposal
        """
        pass

    def test_create_proposal_proposals_post(self) -> None:
        """Test case for create_proposal_proposals_post

        Create Proposal
        """
        pass

    def test_create_vote_proposals_proposal_id_vote_post(self) -> None:
        """Test case for create_vote_proposals_proposal_id_vote_post

        Create Vote
        """
        pass

    def test_delete_proposal_proposals_proposal_id_delete(self) -> None:
        """Test case for delete_proposal_proposals_proposal_id_delete

        Delete Proposal
        """
        pass

    def test_delete_vote_votes_vote_id_delete(self) -> None:
        """Test case for delete_vote_votes_vote_id_delete

        Delete Vote
        """
        pass

    def test_get_votes_proposals_proposal_id_votes_get(self) -> None:
        """Test case for get_votes_proposals_proposal_id_votes_get

        Get Votes
        """
        pass

    def test_read_proposal_proposals_proposal_id_get(self) -> None:
        """Test case for read_proposal_proposals_proposal_id_get

        Read Proposal
        """
        pass

    def test_read_proposals_proposals_get(self) -> None:
        """Test case for read_proposals_proposals_get

        Read Proposals
        """
        pass


if __name__ == '__main__':
    unittest.main()
