# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.proposal import Proposal
from openapi_client.models.proposal_create import ProposalCreate
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.vote import Vote
from openapi_client.models.vote_create import VoteCreate
